name = "NHM4CP"
uuid = "64425ff1-d6a1-417f-9b69-f02c7688ee9d"
authors = ["Jean-Pierre Dussault <vepiteski@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
